//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pactika
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShipment
    {
        public int id { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
